run:
  timeout: 1m

linters:
  enable-all: true
  fast: true

  disable:
    - depguard
    - forbidigo
    - forcetypeassert

    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

issues:
  exclude-use-default: false
