version: "3"

tasks:
  default:
    cmds:
      - task: lint
      - task: build
      - task: run
  skip:
    cmds:
      - task: build
      - task: run
  build:
    cmds:
      - go build -o ./bin/nixup .
  run:
    cmds:
      - ./bin/nixup {{.CLI_ARGS}}
  lint:
    cmds:
      - golangci-lint run ./...
  vhs:
    cmds:
      - vhs ./vhs/nixup.tape
